### ISSUE TITLE
Allow queries without authentication key

### ISSUE THREAD

**Issue by juhp** [product-definition-center/pdc-client#159]
It would be nice if pdc-client could do queries without insisting on having an auth key.
Authentication is only really needed for updating PDC data.

# Version
pdc-client-1.8.0-18.fc32

# Steps to Reproduce:
`$ pdc -s https://pdc.fedoraproject.org rpm list`

# Actual results:
Traceback (most recent call last):
  File "/usr/bin/pdc", line 22, in <module>
    runner.run()
  File "/usr/lib/python3.8/site-packages/pdc_client/runner.py", line 183, in run
    self.client = pdc_client.PDCClientWithPage(self.args.server, page_size=self.args.page_size, ssl_verify=ssl_verify, page=self.args.page)
  File "/usr/lib/python3.8/site-packages/pdc_client/__init__.py", line 407, in __init__
    super(PDCClientWithPage, self).__init__(server, token, develop, ssl_verify, page_size)
  File "/usr/lib/python3.8/site-packages/pdc_client/__init__.py", line 238, in __init__
    token = self.obtain_token()
  File "/usr/lib/python3.8/site-packages/pdc_client/__init__.py", line 256, in obtain_token
    raise Exception('Could not obtain token from any known URL.')
Exception: Could not obtain token from any known URL.

# Expected results:
Read some results without auth key.

**Comment by hluk** [comment]
I wasn't aware that the pdc client and server are still used. I thought [fpdc](https://github.com/fedora-infra/fpdc) (with [fpdc-client](https://github.com/fedora-infra/fpdc-client)) is the new cool thing.

cc @lubomir

**Comment by juhp** [comment]
Ah, so I wasn't aware of fpdc...

It seems to be a library?
